version: 2.1
jobs:
  say-hello:
    environment:
      SHIVA: 777777
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo Hello, Shivaaaaa!
            echo $SHIVA
            pwd
            ls -lha
  print_hello:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "print hello"
          command: "echo just HELLO!"
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "print world"
          command: "echo just WORLD!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print_hello
      - print_world:
        requires: [print_hello]
