version: 2.1
jobs:
  say-hello:
    environment:
      SHIVA: 777777
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo Hello, Shivaaaaa!
            echo $SHIVA
            pwd
            ls /etc/


workflows:
  say-hello-workflow:
    jobs:
      - say-hello

