version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
commands:
  print_pipeline_id:
    description: "test"
    steps:
      - run:
          name: "test"
          command: "echo $CIRCLE_WORKFLOW_ID"
defaults: &defaults
  docker:
    - image: alpine:latest
jobs:
  say-hello:
    environment:
      SHIVA: 777777
      PIPEID:  << pipeline.id >>
      PIPENO: << pipeline.number >>
      GIT: << pipeline.project.git_url >>
    build:
      <<: *defaults
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo $SHIVA_ENV
            echo $PIPEID
            echo $PIPENO
            echo $GIT
            echo Hello, Shivaaaaa!
            echo $SHIVA
            pwd
            ls -lha
  save_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "save pipeline id to file"
          command: "echo << pipeline.id >> > /tmp/my_id.txt"
      - persist_to_workspace:
          root: /tmp/
          paths:
            - my_id.txt
  print_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run:
          name: "print output"
          command: |
            cat /tmp/my_id.txt
  using_command:
    docker:
      - image:

workflows:
  say-hello-workflow:
    jobs:
      - save_output
      - print_output:
          requires: [save_output]
      - print_hello
      - print_world:
          requires: [print_hello]
