version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
defaults: &defaults
  docker:
    - image: alpine:latest
jobs:
  say-hello:
    environment:
      SHIVA: 777777
      PIPEID:  << pipeline.id >>
      PIPENO: << pipeline.number >>
      GIT: << pipeline.project.git_url >>
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo $SHIVA_ENV
            echo $PIPEID
            echo $PIPENO
            echo $GIT
            echo Hello, Shivaaaaa!
            echo $SHIVA
            pwd
            ls -lha
  save_output:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "save pipeline id to file"
          command: "echo << pipeline.id >> > /tmp/my_id.txt"
      - persist_to_workspace:
          root: /tmp/
          paths:
            - my_id.txt
  print_output:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run:
          name: "print output"
          command: |
            cat /tmp/my_id.txt
  using_command:
    <<: *defaults
    steps:
      - print_pipeline_id:
          id: << pipeline.id >> 
  test_fail:
    <<: *defaults
    steps:
      - run: return 0
      - run: 
          command: echo FAILED!
          when: on_fail
workflows:
  say-hello-workflow:
    jobs:
      - save_output
      - print_output:
          requires: [save_output]
      - using_command
      - test_fail