version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  say-hello:
    environment:
      SHIVA: 777777
      PIPEID:  << pipeline.id >>
      PIPENO: << pipeline.number >>
      GIT: << pipeline.project.git_url >>
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo $SHIVA_ENV
            echo $PIPEID
            echo $PIPENO
            echo $GIT
            echo Hello, Shivaaaaa!
            echo $SHIVA
            pwd
            ls -lha
  save_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "save pipeline id to file"
          command: "echo << pipeline.id >> > my_id.txt"
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - my_id.txt
  print_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/dir
      - run:
          name: "print output"
          command: "cat my_id.txt"
  print_hello:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "print hello"
          command: "echo just HELLO!"
  print_world:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "print world"
          command: "echo just WORLD!"

workflows:
  say-hello-workflow:
    jobs:
      - save_output
      - print_output
      - print_hello
      - print_world:
          requires: [print_hello]
